### PR TITLE
Fix console opening on windows, add indentation

### LINKED ISSUE #3: [BUG] Force opens a console window on windows
To reproduce
-
- Download latest release (0.1) for windows
- Launch the app
- ~Profit~ Console opens

### PR DESCRIPTION
**Pull request by ENDERZOMBI102**
fixes #3
changes are under MIT >:)

### CODE REVIEW

**Comment by ENDERZOMBI102** [comment]
@craftablescience plz fix

File: P2Publish.cpp [hunk 1]
```diff
@@ -7,6 +7,12 @@
 #include <QCommonStyle>
 #include <QStyleFactory>
 
+#ifdef WIN32
```
Comment (craftablescience) [inline P2Publish.cpp:10]: Should be `_WIN32` for maximum portability

File: P2Publish.cpp [hunk 2]
```diff
@@ -7,6 +7,12 @@
...
+	#ifdef NDEBUG
```
Comment (craftablescience) [inline P2Publish.cpp:11]: Can be reduced to `#if defined(_WIN32) && defined(NDEBUG)`

**Review by craftablescience — CHANGES_REQUESTED** [review]

**Review by craftablescience — APPROVED** [review]
